import 'package:flutter/material.dart';

List<ThemeData> getThemes(BuildContext context) {
  return [
    // ! Red
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC4646),
        secondary: Color(0xffEC4646),
        error: Color(0xffEC4646),
        surface: Color(0xffEC4646),
        background: Color(0xffEC4646),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      primaryColor: Color(0xffEC4646),
      accentColor: Color(0xffEC4646),
      brightness: Brightness.dark,
      fontFamily: 'FiraSans',
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4646),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC4646),
        secondary: Color(0xffEC4646),
        error: Color(0xffEC4646),
        surface: Color(0xffEC4646),
        background: Color(0xffEC4646),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      primaryColor: Color(0xffEC4646),
      accentColor: Color(0xffEC4646),
      fontFamily: 'FiraSans',
      timePickerTheme: TimePickerThemeData(backgroundColor: Colors.red),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4646),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Ornage
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC6E46),
        secondary: Color(0xffEC6E46),
        error: Color(0xffEC6E46),
        surface: Color(0xffEC6E46),
        background: Color(0xffEC6E46),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.black,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC6E46),
      accentColor: Color(0xffEC6E46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC6E46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC6E46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC6E46),
        secondary: Color(0xffEC6E46),
        error: Color(0xffEC6E46),
        surface: Color(0xffEC6E46),
        background: Color(0xffEC6E46),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC6E46),
      accentColor: Color(0xffEC6E46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC6E46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC6E46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Merigold
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffECA046),
        secondary: Color(0xffECA046),
        error: Color(0xffECA046),
        surface: Color(0xffECA046),
        background: Color(0xffECA046),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffECA046),
      accentColor: Color(0xffECA046),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECA046),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECA046),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffECA046),
        secondary: Color(0xffECA046),
        error: Color(0xffECA046),
        surface: Color(0xffECA046),
        background: Color(0xffECA046),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffECA046),
      accentColor: Color(0xffECA046),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECA046),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECA046),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Gold
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffECD146),
        secondary: Color(0xffECD146),
        error: Color(0xffECD146),
        surface: Color(0xffECD146),
        background: Color(0xffECD146),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffECD146),
      accentColor: Color(0xffECD146),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECD146),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECD146),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffECD146),
        secondary: Color(0xffECD146),
        error: Color(0xffECD146),
        surface: Color(0xffECD146),
        background: Color(0xffECD146),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffECD146),
      accentColor: Color(0xffECD146),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECD146),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECD146),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Lemon
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffECE546),
        secondary: Color(0xffECE546),
        error: Color(0xffECE546),
        surface: Color(0xffECE546),
        background: Color(0xffECE546),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffECE546),
      accentColor: Color(0xffECE546),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECE546),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECE546),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffECE546),
        secondary: Color(0xffECE546),
        error: Color(0xffECE546),
        surface: Color(0xffECE546),
        background: Color(0xffECE546),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffECE546),
      accentColor: Color(0xffECE546),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffECE546),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffECE546),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Blonde
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffE9EC46),
        secondary: Color(0xffE9EC46),
        error: Color(0xffE9EC46),
        surface: Color(0xffE9EC46),
        background: Color(0xffE9EC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffE9EC46),
      accentColor: Color(0xffE9EC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffE9EC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffE9EC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffE9EC46),
        secondary: Color(0xffE9EC46),
        error: Color(0xffE9EC46),
        surface: Color(0xffE9EC46),
        background: Color(0xffE9EC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffE9EC46),
      accentColor: Color(0xffE9EC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffE9EC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffE9EC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Pistachio
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffCBEC46),
        secondary: Color(0xffCBEC46),
        error: Color(0xffCBEC46),
        surface: Color(0xffCBEC46),
        background: Color(0xffCBEC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffCBEC46),
      accentColor: Color(0xffCBEC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffCBEC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffCBEC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffCBEC46),
        secondary: Color(0xffCBEC46),
        error: Color(0xffCBEC46),
        surface: Color(0xffCBEC46),
        background: Color(0xffCBEC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffCBEC46),
      accentColor: Color(0xffCBEC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffCBEC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffCBEC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Seafoam
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff8FEC46),
        secondary: Color(0xff8FEC46),
        error: Color(0xff8FEC46),
        surface: Color(0xff8FEC46),
        background: Color(0xff8FEC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff8FEC46),
      accentColor: Color(0xff8FEC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff8FEC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff8FEC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff8FEC46),
        secondary: Color(0xff8FEC46),
        error: Color(0xff8FEC46),
        surface: Color(0xff8FEC46),
        background: Color(0xff8FEC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff8FEC46),
      accentColor: Color(0xff8FEC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff8FEC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff8FEC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Mint
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff53EC46),
        secondary: Color(0xff53EC46),
        error: Color(0xff53EC46),
        surface: Color(0xff53EC46),
        background: Color(0xff53EC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff53EC46),
      accentColor: Color(0xff53EC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff53EC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff53EC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff8FEC46),
        secondary: Color(0xff8FEC46),
        error: Color(0xff8FEC46),
        surface: Color(0xff8FEC46),
        background: Color(0xff8FEC46),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff8FEC46),
      accentColor: Color(0xff8FEC46),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff8FEC46),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff8FEC46),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Lime
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46EC9C),
        secondary: Color(0xff46EC9C),
        error: Color(0xff46EC9C),
        surface: Color(0xff46EC9C),
        background: Color(0xff46EC9C),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46EC9C),
      accentColor: Color(0xff46EC9C),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46EC9C),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46EC9C),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46EC9C),
        secondary: Color(0xff46EC9C),
        error: Color(0xff46EC9C),
        surface: Color(0xff46EC9C),
        background: Color(0xff46EC9C),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46EC9C),
      accentColor: Color(0xff46EC9C),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46EC9C),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46EC9C),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Sea
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46ECC4),
        secondary: Color(0xff46ECC4),
        error: Color(0xff46ECC4),
        surface: Color(0xff46ECC4),
        background: Color(0xff46ECC4),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46ECC4),
      accentColor: Color(0xff46ECC4),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECC4),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECC4),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46ECC4),
        secondary: Color(0xff46ECC4),
        error: Color(0xff46ECC4),
        surface: Color(0xff46ECC4),
        background: Color(0xff46ECC4),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46ECC4),
      accentColor: Color(0xff46ECC4),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECC4),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECC4),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Teal
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46ECE2),
        secondary: Color(0xff46ECE2),
        error: Color(0xff46ECE2),
        surface: Color(0xff46ECE2),
        background: Color(0xff46ECE2),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46ECE2),
      accentColor: Color(0xff46ECE2),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECE2),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECE2),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46ECE2),
        secondary: Color(0xff46ECE2),
        error: Color(0xff46ECE2),
        surface: Color(0xff46ECE2),
        background: Color(0xff46ECE2),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46ECE2),
      accentColor: Color(0xff46ECE2),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECE2),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECE2),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Cerulean
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46ECE2),
        secondary: Color(0xff46ECE2),
        error: Color(0xff46ECE2),
        surface: Color(0xff46ECE2),
        background: Color(0xff46ECE2),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46ECE2),
      accentColor: Color(0xff46ECE2),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECE2),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECE2),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46ECE2),
        secondary: Color(0xff46ECE2),
        error: Color(0xff46ECE2),
        surface: Color(0xff46ECE2),
        background: Color(0xff46ECE2),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46ECE2),
      accentColor: Color(0xff46ECE2),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46ECE2),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46ECE2),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Sky
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46D8EC),
        secondary: Color(0xff46D8EC),
        error: Color(0xff46D8EC),
        surface: Color(0xff46D8EC),
        background: Color(0xff46D8EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46D8EC),
      accentColor: Color(0xff46D8EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46D8EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46D8EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46D8EC),
        secondary: Color(0xff46D8EC),
        error: Color(0xff46D8EC),
        surface: Color(0xff46D8EC),
        background: Color(0xff46D8EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46D8EC),
      accentColor: Color(0xff46D8EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46D8EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46D8EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Lapis
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46D8EC),
        secondary: Color(0xff46D8EC),
        error: Color(0xff46D8EC),
        surface: Color(0xff46D8EC),
        background: Color(0xff46D8EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46D8EC),
      accentColor: Color(0xff46C4EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46C4EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46C4EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46C4EC),
        secondary: Color(0xff46C4EC),
        error: Color(0xff46C4EC),
        surface: Color(0xff46C4EC),
        background: Color(0xff46C4EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46C4EC),
      accentColor: Color(0xff46C4EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46C4EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46C4EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Berry
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff46C4EC),
        secondary: Color(0xff46C4EC),
        error: Color(0xff46C4EC),
        surface: Color(0xff46C4EC),
        background: Color(0xff46C4EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.black,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff46C4EC),
      accentColor: Color(0xff46C4EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46C4EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46C4EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff46C4EC),
        secondary: Color(0xff46C4EC),
        error: Color(0xff46C4EC),
        surface: Color(0xff46C4EC),
        background: Color(0xff46C4EC),
        onError: Colors.black,
        onPrimary: Colors.black,
        onBackground: Colors.black,
        onSecondary: Colors.black,
        onSurface: Colors.white,
        secondaryVariant: Colors.black,
        primaryVariant: Colors.black,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff46C4EC),
      accentColor: Color(0xff46C4EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff46C4EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff46C4EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.black,
        ),
      ),
    ),

    // ! Azure
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff4692EC),
        secondary: Color(0xff4692EC),
        error: Color(0xff4692EC),
        surface: Color(0xff4692EC),
        background: Color(0xff4692EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff4692EC),
      accentColor: Color(0xff4692EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff4692EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff4692EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff4692EC),
        secondary: Color(0xff4692EC),
        error: Color(0xff4692EC),
        surface: Color(0xff4692EC),
        background: Color(0xff4692EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff4692EC),
      accentColor: Color(0xff4692EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff4692EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff4692EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Blue
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff467EEC),
        secondary: Color(0xff467EEC),
        error: Color(0xff467EEC),
        surface: Color(0xff467EEC),
        background: Color(0xff467EEC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff467EEC),
      accentColor: Color(0xff467EEC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff467EEC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff467EEC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff467EEC),
        secondary: Color(0xff467EEC),
        error: Color(0xff467EEC),
        surface: Color(0xff467EEC),
        background: Color(0xff467EEC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff467EEC),
      accentColor: Color(0xff467EEC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff467EEC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff467EEC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Navy
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff467EEC),
        secondary: Color(0xff467EEC),
        error: Color(0xff467EEC),
        surface: Color(0xff467EEC),
        background: Color(0xff467EEC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff467EEC),
      accentColor: Color(0xff467EEC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff467EEC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff467EEC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff467EEC),
        secondary: Color(0xff467EEC),
        error: Color(0xff467EEC),
        surface: Color(0xff467EEC),
        background: Color(0xff467EEC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff467EEC),
      accentColor: Color(0xff467EEC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff467EEC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff467EEC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Violet
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff5346EC),
        secondary: Color(0xff5346EC),
        error: Color(0xff5346EC),
        surface: Color(0xff5346EC),
        background: Color(0xff5346EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff5346EC),
      accentColor: Color(0xff5346EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff5346EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff5346EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff5346EC),
        secondary: Color(0xff5346EC),
        error: Color(0xff5346EC),
        surface: Color(0xff5346EC),
        background: Color(0xff5346EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff5346EC),
      accentColor: Color(0xff5346EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff5346EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff5346EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Purple
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff7B46EC),
        secondary: Color(0xff7B46EC),
        error: Color(0xff7B46EC),
        surface: Color(0xff7B46EC),
        background: Color(0xff7B46EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff7B46EC),
      accentColor: Color(0xff7B46EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff7B46EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff7B46EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff7B46EC),
        secondary: Color(0xff7B46EC),
        error: Color(0xff7B46EC),
        surface: Color(0xff7B46EC),
        background: Color(0xff7B46EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff7B46EC),
      accentColor: Color(0xff7B46EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff7B46EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff7B46EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Amethyst
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff9946EC),
        secondary: Color(0xff9946EC),
        error: Color(0xff9946EC),
        surface: Color(0xff9946EC),
        background: Color(0xff9946EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xff9946EC),
      accentColor: Color(0xff9946EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff9946EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff9946EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff9946EC),
        secondary: Color(0xff9946EC),
        error: Color(0xff9946EC),
        surface: Color(0xff9946EC),
        background: Color(0xff9946EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xff9946EC),
      accentColor: Color(0xff9946EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xff9946EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xff9946EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Mauve
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffB746EC),
        secondary: Color(0xffB746EC),
        error: Color(0xffB746EC),
        surface: Color(0xffB746EC),
        background: Color(0xffB746EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffB746EC),
      accentColor: Color(0xffB746EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffB746EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffB746EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffB746EC),
        secondary: Color(0xffB746EC),
        error: Color(0xffB746EC),
        surface: Color(0xffB746EC),
        background: Color(0xffB746EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffB746EC),
      accentColor: Color(0xffB746EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffB746EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffB746EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Lavender
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffDF46EC),
        secondary: Color(0xffDF46EC),
        error: Color(0xffDF46EC),
        surface: Color(0xffDF46EC),
        background: Color(0xffDF46EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffDF46EC),
      accentColor: Color(0xffDF46EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffDF46EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffDF46EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffDF46EC),
        secondary: Color(0xffDF46EC),
        error: Color(0xffDF46EC),
        surface: Color(0xffDF46EC),
        background: Color(0xffDF46EC),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffDF46EC),
      accentColor: Color(0xffDF46EC),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffDF46EC),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffDF46EC),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Pink
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC46C7),
        secondary: Color(0xffEC46C7),
        error: Color(0xffEC46C7),
        surface: Color(0xffEC46C7),
        background: Color(0xffEC46C7),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC46C7),
      accentColor: Color(0xffEC46C7),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC46C7),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC46C7),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC46C7),
        secondary: Color(0xffEC46C7),
        error: Color(0xffEC46C7),
        surface: Color(0xffEC46C7),
        background: Color(0xffEC46C7),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC46C7),
      accentColor: Color(0xffEC46C7),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC46C7),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC46C7),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Ruby
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC46AA),
        secondary: Color(0xffEC46AA),
        error: Color(0xffEC46AA),
        surface: Color(0xffEC46AA),
        background: Color(0xffEC46AA),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC46AA),
      accentColor: Color(0xffEC46AA),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC46AA),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC46AA),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC46AA),
        secondary: Color(0xffEC46AA),
        error: Color(0xffEC46AA),
        surface: Color(0xffEC46AA),
        background: Color(0xffEC46AA),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC46AA),
      accentColor: Color(0xffEC46AA),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC46AA),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC46AA),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Brick
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC4696),
        secondary: Color(0xffEC4696),
        error: Color(0xffEC4696),
        surface: Color(0xffEC4696),
        background: Color(0xffEC4696),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC4696),
      accentColor: Color(0xffEC4696),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC4696),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4696),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC4696),
        secondary: Color(0xffEC4696),
        error: Color(0xffEC4696),
        surface: Color(0xffEC4696),
        background: Color(0xffEC4696),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC4696),
      accentColor: Color(0xffEC4696),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC4696),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4696),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Cerise
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC466E),
        secondary: Color(0xffEC466E),
        error: Color(0xffEC466E),
        surface: Color(0xffEC466E),
        background: Color(0xffEC466E),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.black,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC466E),
      accentColor: Color(0xffEC466E),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC466E),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC466E),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC466E),
        secondary: Color(0xffEC466E),
        error: Color(0xffEC466E),
        surface: Color(0xffEC466E),
        background: Color(0xffEC466E),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC466E),
      accentColor: Color(0xffEC466E),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC466E),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC466E),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),

    // ! Fire
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffEC4646),
        secondary: Color(0xffEC4646),
        error: Color(0xffEC4646),
        surface: Color(0xffEC4646),
        background: Color(0xffEC4646),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSurface: Colors.black,
        onSecondary: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.light,
      primaryColor: Color(0xffEC4646),
      accentColor: Color(0xffEC4646),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC4646),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4646),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
    ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffEC4646),
        secondary: Color(0xffEC4646),
        error: Color(0xffEC4646),
        surface: Color(0xffEC4646),
        background: Color(0xffEC4646),
        onError: Colors.white,
        onPrimary: Colors.white,
        onBackground: Colors.white,
        onSecondary: Colors.white,
        onSurface: Colors.white,
        secondaryVariant: Colors.white,
        primaryVariant: Colors.white,
      ),
      brightness: Brightness.dark,
      primaryColor: Color(0xffEC4646),
      accentColor: Color(0xffEC4646),
      fontFamily: 'FiraSans',
      primaryColorDark: Color(0xffEC4646),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: Color(0xffEC4646),
        contentTextStyle: TextStyle(
          fontFamily: 'FiraSans',
          color: Colors.white,
        ),
      ),
    ),
  ];
}
